[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
lalrpop-util = "0.22.1"
lalrpop = { version = "0.22.1", features = ["lexer"] }
